### ISSUE TITLE
Introduction

### ISSUE THREAD

**Issue by SameeraIndika** [SameeraIndika/AS471-Mini-Project-Group-B#1]
Please complete the followings:

1. Purpose
2. Scope of Development Project
3. Definitions & Abbreviations
4. References
   - Books
   - Websites

**Comment by SameeraIndika** [comment]
Noted.

**Comment by SameeraIndika** [comment]
Task Completed.

**Comment by SameeraIndika** [comment]
Rviewed!

**Comment by chathuniwijebandara** [comment]
Reviewed before the submission
